import { NATIONAL_HISTORIC_DATA, NATIONAL_SINGLE_DATA, NATIONAL_WITHOUT_DATE, NATIONAL_WITH_DATE, STATE_HISTORIC_DATA, STATE_SINGLE_DATA, STATE_WITHOUT_DATE, STATE_WITH_DATE } from "../utils/constants";

export type QueryFunction = () => Promise<any>;

export const queryKeyMap: Record<string, typeof STATE_HISTORIC_DATA | typeof STATE_SINGLE_DATA | typeof NATIONAL_SINGLE_DATA | typeof NATIONAL_HISTORIC_DATA> = {
  [STATE_WITH_DATE]: STATE_HISTORIC_DATA,
  [STATE_WITHOUT_DATE]: STATE_SINGLE_DATA,
  [NATIONAL_WITH_DATE]: NATIONAL_SINGLE_DATA,
  [NATIONAL_WITHOUT_DATE]: NATIONAL_HISTORIC_DATA
};